appName: feiqu-front

schedule:
  enabled: false

spring:
  profiles:
    active: dev
    #active: prod
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB

server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
    session:
      timeout: 10m
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
  address: 0.0.0.0
  jetty:
    max-http-post-size: 2MB
  max-http-header-size: 80KB
  connection-timeout: 10000

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.feiqu.**.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:/mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




